# Generated by Django 5.2 on 2025-04-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_readinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
