from django.db import migrations

def update_book_about(apps, schema_editor):
    Book = apps.get_model('base', 'Book')
    
    book_details = {
        "To Kill a Mockingbird": """
            To Kill a Mockingbird is a profound exploration of human nature and moral growth, set in the American South. The story follows young Scout Finch as she observes her father, Atticus, defend a Black man falsely accused of rape. Through Scout's innocent eyes, we witness the deep-seated racial prejudices of 1930s Alabama. The novel masterfully weaves together themes of justice, compassion, and the loss of innocence. Atticus Finch stands as a moral beacon throughout the narrative, teaching his children about empathy and courage. The mysterious character of Boo Radley adds a compelling subplot that parallels the main story's themes of judgment and understanding. Harper Lee's writing captures both the charm of childhood and the harsh realities of adult life. The courthouse scenes are particularly powerful, showcasing the tension between justice and prejudice. The book's impact on American literature and its discussion of civil rights remains significant to this day.
        """,

        "1984": """
            1984 presents a chilling vision of a totalitarian future where independent thought is forbidden. The story follows Winston Smith, a low-ranking party member who secretly rebels against the oppressive regime of Oceania. Orwell's masterpiece explores themes of surveillance, control, and the manipulation of truth through the concept of "doublethink." The novel introduces powerful concepts like Big Brother, thoughtcrime, and the Thought Police that have become part of our cultural lexicon. Through Winston's forbidden romance with Julia, we see the human desire for freedom and connection despite overwhelming oppression. The Ministry of Truth, where Winston works rewriting history, serves as a frightening example of how reality can be manipulated by those in power. The book's exploration of language manipulation through Newspeak shows how controlling language can limit independent thought. The final act of the novel delivers one of literature's most devastating conclusions about the power of authoritarian control. Orwell's prescient warnings about totalitarianism continue to resonate with modern readers.
        """,

        "Pride and Prejudice": """
            Pride and Prejudice is Jane Austen's masterful examination of marriage, social class, and personal growth in Regency-era England. The story primarily follows Elizabeth Bennet, a spirited young woman whose prejudices cloud her judgment of the proud Mr. Darcy. Through their evolving relationship, Austen explores how first impressions and societal expectations can lead to misunderstandings and missed opportunities. The novel skillfully portrays the limited options available to women of the period, particularly regarding marriage and financial security. The supporting characters, from the ridiculous Mr. Collins to the charming but duplicitous Mr. Wickham, provide both comedy and commentary on social conventions. Austen's wit and social commentary remain sharp and relevant even after two centuries. The novel's exploration of the tension between heart and head, pride and prejudice, creates a compelling psychological depth. The transformation of both Elizabeth and Darcy demonstrates how self-awareness leads to personal growth. Their journey from mutual dislike to understanding and love has become a template for romantic literature.
        """,

        "The Great Gatsby": """
            The Great Gatsby is a masterful portrayal of the American Dream during the decadent Jazz Age of the 1920s. Through narrator Nick Carraway's eyes, we witness the mysterious millionaire Jay Gatsby's desperate pursuit of his lost love, Daisy Buchanan. Fitzgerald's prose captures both the glamour and the moral decay of the era with extraordinary beauty and precision. The novel explores themes of wealth, love, decadence, and the corruption of the American Dream. Gatsby's lavish parties serve as a backdrop to examine the hollow nature of materialism and social status. The green light at the end of Daisy's dock becomes a powerful symbol of Gatsby's unreachable dreams and desires. The contrast between old money and new money reveals the rigid class distinctions of the time. The story's tragic conclusion serves as a commentary on the destructive nature of obsession and the impossibility of recreating the past. Fitzgerald's detailed descriptions of the era's excesses create a vivid portrait of the Roaring Twenties.
        """,

        "The Catcher in the Rye": """
            The Catcher in the Rye is a powerful coming-of-age story that follows Holden Caulfield's three-day journey through New York City after being expelled from his boarding school. Salinger's masterpiece captures the raw emotions and alienation of adolescence through Holden's distinctive, colloquial voice. The protagonist's struggle with authenticity and his resistance to the adult world's perceived phoniness forms the novel's core conflict. Through encounters with various characters, Holden's deep-seated grief over his brother Allie's death and his protective feelings toward his sister Phoebe emerge. The novel explores themes of innocence, identity, and the challenging transition from adolescence to adulthood. Holden's desire to be the 'catcher in the rye,' protecting children from falling off a cliff, symbolizes his wish to preserve innocence. The book's honest portrayal of teenage alienation and mental health struggles continues to resonate with readers. Its influence on literature and popular culture remains significant decades after its publication.
        """,

        "The Hobbit": """
            The Hobbit is an enchanting tale that follows Bilbo Baggins, a comfort-loving hobbit who embarks on an unexpected journey across Middle-earth. Tolkien masterfully creates a rich fantasy world filled with dwarves, elves, dragons, and other magical creatures. The story chronicles Bilbo's transformation from a reluctant participant to a crucial hero in the quest to reclaim the Lonely Mountain from the dragon Smaug. Through various challenges and adventures, Bilbo discovers his own courage and resourcefulness, particularly with the help of the mysterious ring he finds. The novel explores themes of heroism, friendship, and the conflict between greed and honor. Tolkien's detailed world-building and vivid descriptions bring Middle-earth to life in remarkable detail. The character development, especially Bilbo's growth from a timid hobbit to a confident adventurer, forms the heart of the narrative. The book's moral complexity increases as the story progresses, culminating in difficult choices about loyalty and righteousness.
        """,

        "Harry Potter and the Philosopher's Stone": """
            Harry Potter and the Philosopher's Stone introduces readers to the magical world through the eyes of an eleven-year-old orphan who discovers he's a wizard. The story follows Harry's first year at Hogwarts School of Witchcraft and Wizardry, where he finds friendship, adventure, and his place in a world he never knew existed. Through encounters with magical creatures, flying lessons, and the mystery of the Philosopher's Stone, Rowling creates a rich and immersive magical universe. The book explores themes of good versus evil, the power of love, and the importance of choices in shaping who we become. The supporting characters, from the loyal Ron Weasley to the brilliant Hermione Granger, add depth and humor to the narrative. The threat of Lord Voldemort provides a dark undertone that balances the wonder and whimsy of the magical world. The novel's detailed world-building establishes the foundation for the entire series, introducing magical concepts and rules that will become crucial in later books. The story's themes of friendship, courage, and standing up to evil resonate with readers of all ages.
        """,

        "The Da Vinci Code": """
            The Da Vinci Code combines historical conspiracy theories, religious symbolism, and fast-paced thriller elements into a compelling narrative. The story follows Harvard symbologist Robert Langdon and cryptographer Sophie Neveu as they unravel a mystery that could shake the foundations of Christianity. Through a series of intricate puzzles and historical clues, the novel explores controversial theories about the Holy Grail and the role of the sacred feminine in Christian history. Brown's research into art, architecture, and religious history creates a rich backdrop for the thriller elements. The chase across Paris and London keeps readers engaged while introducing complex historical and religious concepts. The relationship between Langdon and Neveu develops naturally as they face increasingly dangerous situations. The novel's exploration of the conflict between faith and historical fact raises provocative questions about religious truth. The intricate plot weaves together multiple historical threads into a cohesive and suspenseful narrative.
        """,

        "The Alchemist": """
            The Alchemist is a philosophical novel that follows Santiago, a young Andalusian shepherd, on his journey to discover his Personal Legend. Coelho's masterpiece combines spiritual wisdom with adventure as Santiago travels from Spain to the Egyptian pyramids in search of treasure. The story explores the universal theme of following one's dreams and learning to read the signs of the universe. Through Santiago's encounters with various characters, including the alchemist himself, the novel reveals profound truths about the nature of destiny and personal fulfillment. The book's simple yet powerful prose conveys complex ideas about the unity of all things and the importance of listening to one's heart. Magical elements blend seamlessly with realistic details to create a narrative that operates on multiple levels. The concept of the Soul of the World and its connection to individual destiny forms a central theme. The story's message about the transformative power of pursuing one's dreams has resonated with millions of readers worldwide.
        """,

        "The Lord of the Rings": """
            The Lord of the Rings is an epic high-fantasy masterpiece that follows the perilous quest to destroy the One Ring and defeat the Dark Lord Sauron. Tolkien's trilogy weaves together multiple storylines, focusing on the humble hobbit Frodo Baggins and his journey to Mordor. The narrative explores profound themes of friendship, sacrifice, and the corruption of power through its diverse cast of characters. The detailed world-building creates a complete and believable Middle-earth, complete with its own languages, histories, and mythologies. The story's epic scope encompasses both intimate personal struggles and world-changing events. Through the Fellowship's journey, we see the importance of even the smallest persons in the greatest of quests. The contrast between good and evil is nuanced, showing how power can corrupt even the noblest intentions. The trilogy's influence on the fantasy genre and popular culture cannot be overstated. The rich character development and intricate plot threads create an immersive reading experience.
        """,

        "The Hunger Games": """
            The Hunger Games presents a brutal dystopian future where the Capitol maintains control through an annual televised death match between young tributes from twelve districts. The story follows Katniss Everdeen, who volunteers to take her sister's place in the games, becoming a symbol of rebellion against the oppressive regime. Through the preparation for and execution of the games, Collins explores themes of survival, sacrifice, and the moral cost of violence. The novel's critique of media manipulation and entertainment culture remains particularly relevant in today's world. The complex relationship between Katniss and Peeta adds emotional depth to the survival story. The detailed world-building creates a believable future society while commenting on present-day issues. The supporting characters, from the flamboyant Effie to the troubled Haymitch, add depth to the Capitol's twisted culture. The story's examination of power, propaganda, and resistance resonates with readers of all ages.
        """,

        "The Girl with the Dragon Tattoo": """
            The Girl with the Dragon Tattoo weaves together multiple narratives into a complex thriller that explores themes of corruption, violence against women, and justice. The story follows journalist Mikael Blomkvist and brilliant hacker Lisbeth Salander as they investigate both a decades-old disappearance and a series of brutal murders. Larsson's detailed portrayal of Swedish society provides a stark backdrop for the dark crimes at the heart of the story. The novel's exploration of institutional corruption and family secrets creates layers of mystery that gradually unfold. Lisbeth Salander emerges as a unique and compelling character, her past trauma informing her quest for justice. The investigation into the Vanger family reveals how power and wealth can hide generations of abuse. The relationship between Blomkvist and Salander develops organically through their shared pursuit of truth. The book's unflinching examination of violence and revenge raises questions about morality and justice.
        """,

        "The Road": """
            The Road is a haunting post-apocalyptic novel that follows a father and son's journey through a devastated America. McCarthy's sparse, poetic prose creates a bleak atmosphere that emphasizes the characters' desperate struggle for survival. Through their journey south toward the coast, the novel explores themes of hope, love, and maintaining humanity in a world stripped of civilization. The relationship between father and son forms the emotional core of the story, examining how parental love persists in the face of unimaginable hardship. The novel's minimal punctuation and stripped-down style reflects the stark reality of their world. Brief flashbacks to the time before the apocalypse provide context while maintaining the story's forward momentum. The constant threat from other survivors raises questions about moral choices in a world without society. The novel's exploration of faith and purpose in a seemingly hopeless world resonates deeply with readers.
        """,

        "Life of Pi": """
            Life of Pi is a philosophical adventure that explores faith, survival, and the nature of truth through an extraordinary tale of a boy stranded at sea with a Bengal tiger. The novel follows Pi Patel as he survives a shipwreck only to face 227 days adrift in the Pacific Ocean with an unlikely companion. Through Pi's struggle to survive, Martel examines the relationship between faith and reason, and how stories help us understand reality. The detailed descriptions of life at sea and animal behavior create a vivid and believable world despite the fantastic elements. Pi's background in multiple religions provides a unique lens through which to view his extraordinary experience. The novel's structure, with its frame narrative, raises questions about the nature of truth and storytelling. The relationship between Pi and Richard Parker, the tiger, explores themes of companionship and survival. The book's conclusion challenges readers to consider which version of events they choose to believe.
        """,

        "The Kite Runner": """
            The Kite Runner is a powerful story of redemption that follows Amir's journey from a privileged childhood in Kabul to his eventual return to Afghanistan under Taliban rule. Through the complex relationship between Amir and Hassan, Hosseini explores themes of guilt, betrayal, and the possibility of redemption. The novel's portrayal of Afghanistan's transformation from a monarchy through Soviet occupation to Taliban rule provides a rich historical context. The cultural traditions, particularly the kite fighting tournament, create a vivid picture of pre-war Kabul. Amir's struggle with his past actions drives the narrative forward, leading to a dangerous return to his homeland. The father-son relationships throughout the story examine how parents' choices affect their children's lives. The novel's exploration of class and ethnic divisions in Afghan society adds depth to the personal narrative. The story's message about the possibility of redemption offers hope despite its dark themes.
        """,

        "Gone Girl": """
            Gone Girl is a psychological thriller that deconstructs modern marriage through the lens of a missing person investigation. The story alternates between Nick Dunne's present-day narrative as he deals with his wife's disappearance and Amy's diary entries leading up to her disappearance. Flynn masterfully creates unreliable narrators, forcing readers to constantly question their assumptions about the truth. The novel explores themes of identity, marriage, and the personas we create for others. The media circus surrounding Amy's disappearance provides commentary on how true crime stories are sensationalized. The complex relationship between Nick and Amy reveals how couples can become trapped in destructive patterns. The book's structure, with its dual narratives and unreliable narrators, keeps readers guessing until the end. The novel's dark exploration of marriage and manipulation has influenced the psychological thriller genre. The story's examination of gender roles and expectations adds depth to the thriller elements.
        """,

        "The Martian": """
            The Martian combines hard science fiction with survival storytelling to create a compelling tale of human ingenuity and determination. The story follows astronaut Mark Watney as he struggles to survive alone on Mars after being accidentally left behind by his crew. Through Watney's problem-solving approach to survival, the novel celebrates human intelligence and resourcefulness. The technical details of survival on Mars are presented with accuracy while remaining accessible to general readers. Watney's humor and optimism in the face of seemingly impossible odds provide both comic relief and emotional depth. The international effort to rescue him highlights themes of human cooperation and the value of individual life. The novel's structure, alternating between Watney's logs and events on Earth, maintains suspense while showing the global impact of his situation. The scientific accuracy and attention to detail create a realistic portrayal of Mars exploration.
        """,

        "The Silent Patient": """
            The Silent Patient is a psychological thriller that explores the mystery of why Alicia Berenson shot her husband and then never spoke another word. The story follows criminal psychotherapist Theo Faber as he attempts to uncover the truth behind Alicia's silence. Through Theo's investigation, the novel examines themes of trauma, truth, and the complexity of human psychology. The structure of the narrative, with its careful revelation of information, builds suspense while exploring deeper psychological themes. The setting of the psychiatric facility creates an atmosphere of uncertainty and hidden truths. The relationship between therapist and patient becomes increasingly complex as Theo delves deeper into Alicia's past. The novel's exploration of art and creativity as expressions of suppressed emotion adds depth to the psychological elements. The story's twist ending forces readers to reevaluate everything they thought they knew about the characters.
        """,

        "Dune": """
            Dune is a masterpiece of science fiction that combines political intrigue, religious prophecy, and ecological themes in a richly detailed future universe. The story follows Paul Atreides as his family takes control of the desert planet Arrakis, source of the most valuable substance in the universe. Herbert's world-building creates a complex society with detailed political, religious, and ecological systems. The novel explores themes of power, prophecy, and the consequences of messianic leadership. The indigenous Fremen culture and their relationship with the desert environment form a crucial part of the narrative. The political machinations between noble houses mirror historical power struggles while adding unique science fiction elements. The book's examination of religion and prophecy raises questions about fate and free will. The ecological aspects of the story, particularly regarding water conservation, remain relevant today. The complex characters and their competing motivations create a sophisticated political drama.
        """,

        "The Handmaid's Tale": """
            The Handmaid's Tale presents a dystopian future where religious fundamentalism has stripped women of their rights and reduced them to their reproductive function. The story follows Offred, a Handmaid forced to bear children for the ruling class in the Republic of Gilead. Through Offred's narrative, Atwood explores themes of power, gender, and the fragility of human rights. The novel's structure, with its flashbacks to life before Gilead, shows how quickly society can descend into totalitarianism. The detailed world-building creates a believable and terrifying future through small, everyday details. The relationships between women in different social classes reveal how oppressive systems can turn victims against each other. The novel's exploration of language and how it can be used to control thought remains particularly relevant. The story's examination of religious fundamentalism and its impact on women's rights continues to resonate with modern readers.
        """
    }
    
    for book in Book.objects.all():
        if book.title in book_details:
            book.about = book_details[book.title].strip()
            book.save()
        else:
            book.about = book.short_description
            book.save()

def reverse_book_about(apps, schema_editor):
    Book = apps.get_model('base', 'Book')
    Book.objects.all().update(about='')

class Migration(migrations.Migration):
    dependencies = [
        ('base', '0008_book_about'),
    ]

    operations = [
        migrations.RunPython(update_book_about, reverse_book_about),
    ]
